export { default as autobind } from './methods/autobind'
export { default as decorate } from './methods/decorate'
export { default as time } from './methods/time'

export { default as configurable } from './prop/configurable'
export { default as enumerable } from './prop/enumerable'
export { default as extendDescriptor } from './prop/extendDescriptor'
export { default as nonconfigurable } from './prop/lazyinit'
export { default as nonenumerable } from './prop/lazyinit'
export { default as readonly } from './prop/lazyinit'
export { default as getter } from './prop/getter'
export { default as setter } from './prop/setter'